config/routes.rb
Barcamp::Application.routes.draw do
  resources :registrations

  root :to => 'high_voltage/pages#show', :id => 'home'
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  TSHIRT_SIZES = [
    "Men's Small",
    "Men's Medium",
    "Men's Large",
    "Men's X-Large",
    "Men's XX-Large",
    "Men's XXX-Large",    
    "Women's Small",
    "Women's Medium",
    "Women's Large",
    "Women's X-Large",
    "Women's XX-Large",
  ]

  attr_accessible :email, :name, :topic, :twitter, :tshirt_size

  validates_uniqueness_of :name, :email
  validates_uniqueness_of :twitter, allow_nil: true, allow_blank: true
  validates_presence_of :name, :email
  validates_format_of :email, with: %r/.+\@.+\..+/
  validates_format_of :twitter, with: %r/\A@?[A-Za-z0-9_]+\Z/, allow_nil: true, allow_blank: true
  validates_inclusion_of :tshirt_size, in: TSHIRT_SIZES, message: "is missing, please pick a t-shirt size!"

  before_create do
    self.key = SecureRandom.hex(32)
  end

  def twitter_handle
    %<@#{twitter.gsub(/^@/, '')}>
  end

  def gravatar_hash
    Digest::MD5.hexdigest(email.strip.downcase)
  end

  def display_name
    first, last = name.split(" ", 2)
    if last
      "#{first} #{last.first}."
    else
      first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @registration = Registration.new
  end

  def create
    @registration = Registration.new(params[:registration])
    if @registration.save
      Notifier.confirmation(@registration).deliver
      flash[:success] = "Thanks for registering! You'll get an email soon confirming it. See you at BarCamp!"
      redirect_to registrations_path
    else
      render :new
    end
  end

  def index
    @registrations = Registration.all
  end

  def edit
    @registration = Registration.find_by_key!(params[:id])
  end

  def update
    @registration = Registration.find_by_key!(params[:id])

    if @registration.update_attributes(params[:registration])
      flash[:success] = "Updated your info! Thanks!"
      redirect_to registrations_path
    else
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BarCamp Buffalo: Buffalo's Tech Unconference</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="top">
    <h1><%= link_to "BarCamp Buffalo", root_path %></h1>
  </div>

  <div id="nav">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Info", page_path("info") %></li>
      <li><%= link_to "Register", new_registration_path %></li>
      <li><%= link_to "Attendees (#{Registration.count})", registrations_path %></li>
      <li><%= link_to "Directions", "https://goo.gl/maps/nQWUM" %></li>
      <li><%= link_to "#BarCampBUF", "https://twitter.com/search/realtime?q=%23BarCampBUF" %>
    </ul>
  </div>

  <div id="content">
    <h1>BarCamp Buffalo</h1>
    <h3>Buffalo's Tech Unconference</h3>

    <div id="flash">
      <% flash.each do |key, value| -%>
        <div id="flash_<%= key %>"><%= value %></div>
      <% end -%>
    </div>

    <%= yield %>
  </div>

  <div id="footer">
    This site is <a href="http://github.com/coworkbuffalo/barcampbuffalo">open source</a>. Thanks to <a href="http://barcamproc.org">BarCamp Rochester</a> for letting us borrow their styles!
  </div>
</body>
</html>

app/views/notifier/confirmation.text.erb
Thanks for registering!
=======================

Hey there! You're all set to attend BarCamp Buffalo 7, <%= @registration.name %>! Here's few notes and reminders:

* Not sure how BarCamp will work? This page will explain it all:

<%= page_url('info') %>

* Here's a link for directions to the event:

https://goo.gl/maps/nQWUM

* Changed your talk title, or have an idea for one? Use this URL to change it:

<%= edit_registration_url @registration.key %>

* If you're a UB student and would like a bus ride to/from the event, please email Hadar Borden to schedule a pickup:

hborden@buffalo.edu

See you at BarCamp!

- The BarCampBuffalo Organizers

app/views/notifier/reminder.text.erb
Reminder: Barcamp Buffalo 7 is on 4/26/14!
=========================================

Hey there! Just a quick reminder: BarCamp Buffalo is coming up next weekend! Here's some reminders:

* We now have tshirts, thanks to You and Who! Please fill out your shirt size at this URL if you haven't already:

<%= edit_registration_url @registration.key %>

* Are you a UB student and would like a bus ride to/from the event? Please email Hadar Borden to schedule a pickup:

hborden@buffalo.edu

All other up-to-date info will be on our homepage or on Twitter:

http://twitter.com/barcampbuffalo

http://barcampbuffalo.org/

See you at BarCamp!

- The BarCampBuffalo Organizers

app/views/pages/home.html.erb
<p>
  <b>BarCamp Buffalo (rebooted!)</b> is an ad-hoc gathering born from the desire for people to share and learn in an open environment. BarCamp Buffalo is an 
  intense event with discussions, demos, and interaction from attendees. No spectators, only participants. All attendees should give a demo, a session, or help with one. Anyone with something to contribute or with the desire to learn is welcome and invited to join.
</p>

<p>
 If you attended a prior BarCamp Buffalo, we lacked space and had altered the format -- expect the real deal now that we have lots of space (30-min presentations, multiple presentations in different rooms at every moment to give you greater choices).
</p>

<p>
  Follow <a href="https://twitter.com/BarCampBuffalo">@BarCampBuffalo</a> for more real-time updates about the events. Also check out <a href="http://www.facebook.com/BarCampBuffalo">BarCampBuffalo on Facebook</a> to get updates on future BarCamps!
</p>

<h2>BarCamp Buffalo #7</h3>
<p>
  BarCamp Buffalo is <b>April 26th, 2014</b> at The Foundry with 4 classrooms for 4 tracks of talks going on all at once. 30 mins each. If you've ever been to Rochester's BarCamp, or Buffalo BarCamp #6 in 2013, this will be just like it.

  <ul>
    <li><b>8:00 am</b>: Doors! Breakfast Burritos from Lloyd Taco Truck and registration</li>
    <li><b>9:00 am</b>: Welcome and Intro's</li>
    <li><b>9:30 am</b>: Talks begin!</li>
    <li><b>12:30 pm</b>: More Lloyd, tacos this time, for lunch</li>    
    <li><b>5:00 pm</b>: Wrap up and meetup for after party</li>
  </ul>
</p>

<h2>Directions</h2>

<div id="gMap">
  Here's <a href="http://goo.gl/maps/b2Dcy">a map to The Foundry</a>.</small>
  <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2922.3472762903084!2d-78.8561025!3d42.9077164!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89d3128c300d47f5%3A0x7396ab29c1332b74!2sThe+Foundry!5e0!3m2!1sen!2sus!4v1394024791880" width="600" height="450" frameborder="0" style="border:0"></iframe>
</div>

<p>
  <b>Parking:</b> Street parking should be widely available, you just might have to walk a little(gasp!)
</p>

<h2>2014 Sponsors</h2>

<ul id="sponsors">

	<li><a href="http://att.com/"><%= image_tag "atandt.png" %></a></li>
	<li><a href="http://colliganlaw.com/"><%= image_tag "colliganlaw.jpg" %></a></li>	
	<li><a href="http://43north.org/"><%= image_tag "43north.png" %></a></li>
	<li><a href="http://whereslloyd.com/"><%= image_tag "lloyd.png" %></a></li>
	<li><a href="http://coachmeplus.com/"><%= image_tag "CoachMeLogo.png" %></a></li>  
	<li><a href="http://www.campuslabs.com"><%= image_tag "campuslabs.png" %></a></li> 
	<li><a href="http://infotechniagara.org/"><%= image_tag "infotech_logo.png" %></a></li>
	<li><a href="http://youandwho.com/"><%= image_tag "you-and-who.jpg" %></a></li>
	<li><a href="https://www.facebook.com/HeadsUpDisplay"><%= image_tag "headsup.png" %></a></li>
	<li><a href="http://nicholasbarone.com/">Nicholas Barone</a></li>  	 
	<li>Boot Sector</li>

</ul>

<p>
  Email <a href="mailto:dan.gigante@gmail.com">Dan Gigante</a> for information on supporting this event and ensuring the all-volunteer effort behind this event can continue to make these happen for the Buffalo tech community. Thank you for your support!</a>
</p>

app/views/pages/info.html.erb
<div id="info">
  <h2>Info about BarCamp Buffalo</h2>
  <p>
    Never been to BarCamp Buffalo? Never been to any BarCamp? It can be a little intimidating to be told that if you attend, you should present. At BarCamp Buffalo, we are a little looser on those rules, because we understand the intimidation factor. We would rather you come and just experience it, than not come because you don't have a presentation. Hopefully after reading this page, you'll understand what happens at BarCamp Buffalo, and maybe you'll be more comfortable going in.
  </p>
  <p>
    <b>UB Students!</b> Need a ride to BarCamp Buffalo? Send an email to <%= mail_to "hborden@buffalo.edu", "Hadar Borden", encode: "hex" %> to schedule a pickup.
  </p>
  <div class="howToHeading hth_before"><div class="howToHeadingText">Before BarCamp</div></div>
  <div class="eventTimeDetails">
    <h2>Register for BarCamp Buffalo</h2>
    <p>
      Registration is extremely important for us. BarCamp is free, and we accept anyone, even if they sign up day of, but we like to have approximate numbers about a week before the event. This helps us coordinate food and t-shirt purchases. So head on over to <% link_to "our registration page", new_registration_path %> and sign up! If you do plan to present, you don't have to know your topic yet, just fill it out before the event!
    </p>
    <h2>Prepare a Presentation</h2>
    <p>
      Even if you are nervous about presenting, or don't want to present... come up with something you are passionate about, and prepare a 20-30 minute presentation. We will not make you present it if you are not comfortable. Once you have a presentation though, you <i>can</i> present if you choose to. Many first time attendees, after watching the first presentations of the day, are much more comfortable giving their own in the afternoon. Make sure you print any notes you might need - just in case there are projection technical difficulties.
    </p>
    <h2>Tell Your Friends</h2>
    <p>
      BarCamp is nothing without it's <%= link_to "attendees", registrations_path %>. The more people that come to BarCamp, the better! Have a friend that might be interested in learning something new? A friend that is doing something really cool at work, or as a side project? Invite them! BarCamp Buffalo is free, and you get free stuff! Check it out, and invite others to experience it. Worst case scenario? You get a good meal, a t-shirt, and a little less sleep that morning.
    </p>
  </div>
  <div class="howToHeading hth_during"><div class="howToHeadingText">During BarCamp</div></div>
  <div class="eventTimeDetails">
    <h2>Watch Presentations</h2>
    <p>Check out presentations about stuff you are already interested in. Throw in some other presentations about stuff you've never heard about. Tweet about what is awesome (or maybe about what is horrible?). Ask questions, be involved.</p>
    <h2>Give Your Own Presentation</h2>
    <p>Now that you've seen a few presentations, and aren't as intimidated as you were before you woke up, throw your placard on the wall on give one yourself. Talk about something you care about, and you can share that passion with others. It's rewarding and exciting. Presentations should be about 10 minutes with 5 minutes at the end for questions and answers (and setup time for the next presenter).</p>
  </div>

  <div class="howToHeading hth_after" ><div class="howToHeadingText">After BarCamp</div></div>
  <div class="eventTimeDetails">
    <h2>Write about BarCamp Buffalo</h2>
    <p>Do you have a blog? Write about your experience - positive OR negative. We really hope it was a positive experience, but let us know if it wasn't. Tell your friends what is was like. Make sure to follow the people you met on twitter. Keep the conversation going, and build friendship and relationships. When the next event approaches, if you liked this one, promote it yourself and get excited about coming up with another presentation about something you are passionate about.</p>
    <h2>Get Involved</h2>
    <p>We are always looking for help. If you have an idea that you can help implement, let us know, tweet at us! If you work for a company that likes to sponsor these kinds of events, let the people who make those decisions know about us. Tell them what you thought, and if it's valuable to them. BarCamp Buffalo is only successful because of people like you who come to our events and make it what it is.</p>
  </div>
</div>

app/views/pages/slides.html.erb
<p>
  Past presentations and more, coming soon!
</p>